"""Add audit_logs table

Revision ID: 61feb3ab57f3
Revises: 9afa630bad08
Create Date: 2026-09-30 10:57:23.868321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '61feb3ab57f3'
down_revision: Union[str, None] = '9afa630bad08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'TENANT_CREATED', 'TENANT_UPDATED', 'TENANT_ACTIVATED', 'TENANT_DEACTIVATED', 'TENANT_SUSPENDED', 'SUBSCRIPTION_PLAN_CREATED', 'SUBSCRIPTION_PLAN_UPDATED', 'SUBSCRIPTION_PLAN_ACTIVATED', 'SUBSCRIPTION_PLAN_DEACTIVATED', 'TENANT_SUBSCRIPTION_PLAN_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_ACTIVATED', 'USER_DEACTIVATED', name='audit_log_action_enum', create_constraint=True), nullable=False),
    sa.Column('resource_type', sa.Enum('TENANT', 'USER', 'SUBSCRIPTION_PLAN', 'AUTHENTICATION', name='audit_log_resource_type_enum', create_constraint=True), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('old_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index('uq_users_email_per_tenant', table_name='users', postgresql_where='(tenant_id IS NOT NULL)')
    op.drop_index('uq_users_email_super_admin', table_name='users', postgresql_where='(tenant_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_email_super_admin', 'users', ['email'], unique=True, postgresql_where='(tenant_id IS NULL)')
    op.create_index('uq_users_email_per_tenant', 'users', ['tenant_id', 'email'], unique=True, postgresql_where='(tenant_id IS NOT NULL)')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
