"""Change profile_image_url to Text for base64

Revision ID: 71014cbe3bdb
Revises: 8001ccec6a76
Create Date: 2026-10-01 11:58:47.576853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71014cbe3bdb'
down_revision: Union[str, None] = '8001ccec6a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image_url',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
