"""Add missing indices

Revision ID: 74088b87a778
Revises: 61feb3ab57f3
Create Date: 2026-09-30 10:58:10.290229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74088b87a778'
down_revision: Union[str, None] = '61feb3ab57f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_email_per_tenant', 'users', ['tenant_id', 'email'], unique=True, postgresql_where='tenant_id IS NOT NULL')
    op.create_index('uq_users_email_super_admin', 'users', ['email'], unique=True, postgresql_where='tenant_id IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_email_super_admin', table_name='users', postgresql_where='tenant_id IS NULL')
    op.drop_index('uq_users_email_per_tenant', table_name='users', postgresql_where='tenant_id IS NOT NULL')
    # ### end Alembic commands ###
