"""Add phone and profile image to user

Revision ID: 8001ccec6a76
Revises: 0034893f7202
Create Date: 2026-09-30 17:46:41.213232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8001ccec6a76'
down_revision: Union[str, None] = '0034893f7202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=1024), nullable=True))
    op.drop_index('uq_users_email_per_tenant', table_name='users', postgresql_where='(tenant_id IS NOT NULL)')
    op.drop_index('uq_users_email_super_admin', table_name='users', postgresql_where='(tenant_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_email_super_admin', 'users', ['email'], unique=True, postgresql_where='(tenant_id IS NULL)')
    op.create_index('uq_users_email_per_tenant', 'users', ['tenant_id', 'email'], unique=True, postgresql_where='(tenant_id IS NOT NULL)')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
