"""Add subscription plans

Revision ID: 815b2665316c
Revises: f8fde2f43f6e
Create Date: 2026-09-29 19:35:14.421858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '815b2665316c'
down_revision: Union[str, None] = 'f8fde2f43f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    billing_cycle_enum = postgresql.ENUM('MONTHLY', 'YEARLY', name='billing_cycle_enum', create_type=False)
    billing_cycle_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_cycle', billing_cycle_enum, nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=False),
    sa.Column('max_leads', sa.Integer(), nullable=False),
    sa.Column('max_ai_usage', sa.Integer(), nullable=False),
    sa.Column('max_storage', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.create_foreign_key('fk_tenants_subscription_plan_id', 'tenants', 'subscription_plans', ['subscription_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_subscription_plan_id', 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    
    postgresql.ENUM(name="billing_cycle_enum").drop(op.get_bind())
    # ### end Alembic commands ###
