"""Add audit logs

Revision ID: 9afa630bad08
Revises: 815b2665316c
Create Date: 2026-09-29 19:47:38.313632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9afa630bad08'
down_revision: Union[str, None] = '815b2665316c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    audit_log_action_enum = postgresql.ENUM('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'TENANT_CREATED', 'TENANT_UPDATED', 'TENANT_ACTIVATED', 'TENANT_DEACTIVATED', 'TENANT_SUSPENDED', 'SUBSCRIPTION_PLAN_CREATED', 'SUBSCRIPTION_PLAN_UPDATED', 'SUBSCRIPTION_PLAN_ACTIVATED', 'SUBSCRIPTION_PLAN_DEACTIVATED', 'TENANT_SUBSCRIPTION_PLAN_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_ACTIVATED', 'USER_DEACTIVATED', name='audit_log_action_enum', create_type=False)
    audit_log_action_enum.create(op.get_bind(), checkfirst=True)
    
    audit_log_resource_type_enum = postgresql.ENUM('TENANT', 'USER', 'SUBSCRIPTION_PLAN', 'AUTHENTICATION', name='audit_log_resource_type_enum', create_type=False)
    audit_log_resource_type_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', audit_log_action_enum, nullable=False),
    sa.Column('resource_type', audit_log_resource_type_enum, nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    
    postgresql.ENUM(name="audit_log_action_enum").drop(op.get_bind())
    postgresql.ENUM(name="audit_log_resource_type_enum").drop(op.get_bind())
    # ### end Alembic commands ###
