"""add_billing_cycles_table

Revision ID: d851c8930dca
Revises: 1d77fdc27f56
Create Date: 2026-09-30 16:12:56.744984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd851c8930dca'
down_revision: Union[str, None] = '1d77fdc27f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_cycles_slug'), 'billing_cycles', ['slug'], unique=True)
    op.alter_column('subscription_plans', 'billing_cycle',
               existing_type=postgresql.ENUM('MONTHLY', 'YEARLY', name='billing_cycle_enum'),
               type_=sa.String(length=100),
               existing_nullable=False,
               postgresql_using="billing_cycle::varchar")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'billing_cycle',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('MONTHLY', 'YEARLY', name='billing_cycle_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_billing_cycles_slug'), table_name='billing_cycles')
    op.drop_table('billing_cycles')
    # ### end Alembic commands ###
