"""Update tenant model with full details

Revision ID: f8fde2f43f6e
Revises: 0001_initial
Create Date: 2026-09-29 18:59:32.103085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f8fde2f43f6e'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('timezone', sa.String(length=50), nullable=True))
    tenant_status_enum = postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='tenant_status_enum', create_type=False)
    tenant_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('tenants', sa.Column('status', tenant_status_enum, nullable=False, server_default='ACTIVE'))
    op.add_column('tenants', sa.Column('subscription_plan_id', sa.UUID(), nullable=True))
    op.add_column('tenants', sa.Column('created_by', sa.UUID(), nullable=True))
    op.drop_constraint('uq_tenants_slug', 'tenants', type_='unique')
    op.create_foreign_key('fk_tenants_created_by', 'tenants', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('tenants', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint('fk_tenants_created_by', 'tenants', type_='foreignkey')
    op.create_unique_constraint('uq_tenants_slug', 'tenants', ['slug'])
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenants', 'subscription_plan_id')
    op.drop_column('tenants', 'status')
    
    postgresql.ENUM(name="tenant_status_enum").drop(op.get_bind())
    op.drop_column('tenants', 'timezone')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'company_size')
    op.drop_column('tenants', 'industry')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'legal_name')
    # ### end Alembic commands ###
